'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Food
    Public Property Id As Integer
    Public Property Name As String
    Public Property Price As Decimal
    Public Property ImageUrl As String
    Public Property Quantity As Integer

End Class
